line.bot:
  channel-token: W07WsmG4bJM9PzUeEoFP5hGmotK2PWXOug8BQrRY4oJ5lUIvO7PwYA5YSJPdkRodcIqofnPUnd7dWCsAhsObCH5QKo4hNHce/xnXqkyofTpUks03Q8c0RN84+5LSRgTypq7H3D/qYzs+J3Ll/MD5CwdB04t89/1O/w1cDnyilFU=
  channel-secret: 3d880b0cf9e6b53c63ceb32462d54615
  handler.path: /callback