line.bot:
  channel-token: fI6H98fLh5x5IsaG4jHHnY8CL5Prc6BtwHleq+uRUZtZlOGQbfXc91WteF9H/jo7o7w5VQEIxPGhWfTkJ7vaAMexRBaJPGYjd4bZfebM1Mh263A/DgqYtJ4ACFYcZ59WmVHeuX32I7EYNqIBjnxVcwdB04t89/1O/w1cDnyilFU=
  channel-secret: f1e15e0344d147a8913e4733eae4e6e2
  handler.path: /callback